-- ═══════════════════════════════════════════════════════════════
--  MEDITIMET — 244 rreshta, të gjeneruara nga katalogu
--  Prodhuar nga: scripts/build-meditations-sql.mjs — mos e redakto me dorë.
--
--  ⚠️  Hyjnë si TË PUBLIKUARA, me një rrugë audio të planifikuar. Skedarët
--      nuk ekzistojnë ende, ndaj luajtja dështon derisa të ngarkohen te
--      meditime/<teknika>/<titulli>.mp3. Metadata, drynat dhe rrugëtimi
--      punojnë që tani.
--
--      Për t'i fshehur derisa audio të jetë gati:
--        UPDATE meditations SET published_at = NULL;
--
--  Falas janë 0: një për ankthin, një për zemrën, një për trurin.
-- ═══════════════════════════════════════════════════════════════

SET NAMES utf8mb4;

-- Tabela e përkohshme mban slug-un e teknikës dhe të kategorisë; id-të e vërteta
-- gjenden me JOIN, sepse janë UUID të krijuara gjatë importit të skemës.
DROP TEMPORARY TABLE IF EXISTS tmp_meditations;
CREATE TEMPORARY TABLE tmp_meditations (
  title          VARCHAR(200) NOT NULL,
  subgroup       VARCHAR(120) NOT NULL,
  technique_slug VARCHAR(80)  NOT NULL,
  category_slug  VARCHAR(80)  NOT NULL,
  duration_sec   INT          NOT NULL,
  audio_url      VARCHAR(255) NOT NULL,
  description    TEXT         NULL,
  is_premium     TINYINT(1)   NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO tmp_meditations
  (title, subgroup, technique_slug, category_slug, duration_sec, audio_url, description, is_premium)
VALUES
  ('Liro ankthin në 10 minuta', 'Emocione', 'meditime-riprogramimi', 'emocionet', 600, 'meditime/meditime-riprogramimi/liro-ankthin-ne-10-minuta.mp3', 'Liro ankthin në 10 minuta — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Dil nga paniku', 'Emocione', 'meditime-riprogramimi', 'emocionet', 600, 'meditime/meditime-riprogramimi/dil-nga-paniku.mp3', 'Dil nga paniku — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Qetëso zemërimin', 'Emocione', 'meditime-riprogramimi', 'emocionet', 600, 'meditime/meditime-riprogramimi/qeteso-zemerimin.mp3', 'Qetëso zemërimin — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Shkrij trishtimin', 'Emocione', 'meditime-riprogramimi', 'emocionet', 600, 'meditime/meditime-riprogramimi/shkrij-trishtimin.mp3', 'Shkrij trishtimin — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Largo fajin', 'Emocione', 'meditime-riprogramimi', 'emocionet', 600, 'meditime/meditime-riprogramimi/largo-fajin.mp3', 'Largo fajin — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Largo turpin', 'Emocione', 'meditime-riprogramimi', 'emocionet', 600, 'meditime/meditime-riprogramimi/largo-turpin.mp3', 'Largo turpin — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Kapërce zilinë', 'Emocione', 'meditime-riprogramimi', 'emocionet', 600, 'meditime/meditime-riprogramimi/kaperce-ziline.mp3', 'Kapërce zilinë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Liro xhelozinë', 'Emocione', 'meditime-riprogramimi', 'emocionet', 600, 'meditime/meditime-riprogramimi/liro-xhelozine.mp3', 'Liro xhelozinë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Çliro frikën', 'Emocione', 'meditime-riprogramimi', 'emocionet', 600, 'meditime/meditime-riprogramimi/cliro-friken.mp3', 'Çliro frikën — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Përballo pasigurinë', 'Emocione', 'meditime-riprogramimi', 'emocionet', 600, 'meditime/meditime-riprogramimi/perballo-pasigurine.mp3', 'Përballo pasigurinë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Liro mërzinë', 'Emocione', 'meditime-riprogramimi', 'emocionet', 600, 'meditime/meditime-riprogramimi/liro-merzine.mp3', 'Liro mërzinë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Qetëso mendimet obsesive', 'Emocione', 'meditime-riprogramimi', 'emocionet', 600, 'meditime/meditime-riprogramimi/qeteso-mendimet-obsesive.mp3', 'Qetëso mendimet obsesive — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Rikthe shpresën', 'Emocione', 'meditime-riprogramimi', 'emocionet', 600, 'meditime/meditime-riprogramimi/rikthe-shpresen.mp3', 'Rikthe shpresën — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Ndërprit mbingarkesën emocionale', 'Emocione', 'meditime-riprogramimi', 'emocionet', 600, 'meditime/meditime-riprogramimi/nderprit-mbingarkesen-emocionale.mp3', 'Ndërprit mbingarkesën emocionale — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Hap zemrën', 'Zemra', 'meditime-per-zemren', 'zemra-plot', 600, 'meditime/meditime-per-zemren/hap-zemren.mp3', 'Hap zemrën — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Aktivizo dhembshurinë', 'Zemra', 'meditime-per-zemren', 'zemra-plot', 600, 'meditime/meditime-per-zemren/aktivizo-dhembshurine.mp3', 'Aktivizo dhembshurinë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Fal veten', 'Zemra', 'meditime-per-zemren', 'falja', 600, 'meditime/meditime-per-zemren/fal-veten.mp3', 'Fal veten — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Fal dikë', 'Zemra', 'meditime-per-zemren', 'falja', 600, 'meditime/meditime-per-zemren/fal-dike.mp3', 'Fal dikë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Liro dhimbjen e tradhtisë', 'Zemra', 'meditime-per-zemren', 'zemra-plot', 600, 'meditime/meditime-per-zemren/liro-dhimbjen-e-tradhtise.mp3', 'Liro dhimbjen e tradhtisë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Shëro ndarjen', 'Zemra', 'meditime-per-zemren', 'zemra-plot', 600, 'meditime/meditime-per-zemren/shero-ndarjen.mp3', 'Shëro ndarjen — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Rikthe besimin', 'Zemra', 'meditime-per-zemren', 'zemra-plot', 600, 'meditime/meditime-per-zemren/rikthe-besimin.mp3', 'Rikthe besimin — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Ndje dashurinë pa kushte', 'Zemra', 'meditime-per-zemren', 'zemra-plot', 600, 'meditime/meditime-per-zemren/ndje-dashurine-pa-kushte.mp3', 'Ndje dashurinë pa kushte — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Meditim për marrëdhënien në çift', 'Zemra', 'meditime-per-zemren', 'zemra-plot', 600, 'meditime/meditime-per-zemren/meditim-per-marredhenien-ne-cift.mp3', 'Meditim për marrëdhënien në çift — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Para një interviste', 'Vetëbesimi', 'meditime-riprogramimi', 'vetebesim', 600, 'meditime/meditime-riprogramimi/para-nje-interviste.mp3', 'Para një interviste — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Para një prezantimi', 'Vetëbesimi', 'meditime-riprogramimi', 'vetebesim', 600, 'meditime/meditime-riprogramimi/para-nje-prezantimi.mp3', 'Para një prezantimi — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Para një fjalimi', 'Vetëbesimi', 'meditime-riprogramimi', 'vetebesim', 600, 'meditime/meditime-riprogramimi/para-nje-fjalimi.mp3', 'Para një fjalimi — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Para kamerës', 'Vetëbesimi', 'meditime-riprogramimi', 'vetebesim', 600, 'meditime/meditime-riprogramimi/para-kameres.mp3', 'Para kamerës — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Para një takimi biznesi', 'Vetëbesimi', 'meditime-riprogramimi', 'vetebesim', 600, 'meditime/meditime-riprogramimi/para-nje-takimi-biznesi.mp3', 'Para një takimi biznesi — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Para negociatave', 'Vetëbesimi', 'meditime-riprogramimi', 'vetebesim', 600, 'meditime/meditime-riprogramimi/para-negociatave.mp3', 'Para negociatave — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Rrit karizmën', 'Vetëbesimi', 'meditime-riprogramimi', 'vetebesim', 600, 'meditime/meditime-riprogramimi/rrit-karizmen.mp3', 'Rrit karizmën — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Aktivizo liderin', 'Vetëbesimi', 'meditime-riprogramimi', 'vetebesim', 600, 'meditime/meditime-riprogramimi/aktivizo-liderin.mp3', 'Aktivizo liderin — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Aktivizo autoritetin', 'Vetëbesimi', 'meditime-riprogramimi', 'vetebesim', 600, 'meditime/meditime-riprogramimi/aktivizo-autoritetin.mp3', 'Aktivizo autoritetin — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Fokus ekstrem', 'Truri', 'meditime-per-trurin', 'tru-i-fuqizuar', 600, 'meditime/meditime-per-trurin/fokus-ekstrem.mp3', 'Fokus ekstrem — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Kujtesë më e mirë', 'Truri', 'meditime-per-trurin', 'tru-i-fuqizuar', 600, 'meditime/meditime-per-trurin/kujtese-me-e-mire.mp3', 'Kujtesë më e mirë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Studim intensiv', 'Truri', 'meditime-per-trurin', 'tru-i-fuqizuar', 600, 'meditime/meditime-per-trurin/studim-intensiv.mp3', 'Studim intensiv — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Për provime', 'Truri', 'meditime-per-trurin', 'tru-i-fuqizuar', 600, 'meditime/meditime-per-trurin/per-provime.mp3', 'Për provime — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Për moshën mbi 50 vjeç', 'Truri', 'meditime-per-trurin', 'tru-i-fuqizuar', 600, 'meditime/meditime-per-trurin/per-moshen-mbi-50-vjec.mp3', 'Për moshën mbi 50 vjeç — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Kreativitet', 'Truri', 'meditime-per-trurin', 'tru-i-fuqizuar', 600, 'meditime/meditime-per-trurin/kreativitet.mp3', 'Kreativitet — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Vendimmarrje', 'Truri', 'meditime-per-trurin', 'tru-i-fuqizuar', 600, 'meditime/meditime-per-trurin/vendimmarrje.mp3', 'Vendimmarrje — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Intuitë', 'Truri', 'meditime-per-trurin', 'intuita', 600, 'meditime/meditime-per-trurin/intuite.mp3', 'Intuitë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Zgjidh probleme', 'Truri', 'meditime-per-trurin', 'tru-i-fuqizuar', 600, 'meditime/meditime-per-trurin/zgjidh-probleme.mp3', 'Zgjidh probleme — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Mendo qartë', 'Truri', 'meditime-per-trurin', 'tru-i-fuqizuar', 600, 'meditime/meditime-per-trurin/mendo-qarte.mp3', 'Mendo qartë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Fli shpejt', 'Gjumi', 'meditime-per-trupin', 'gjumi', 600, 'meditime/meditime-per-trupin/fli-shpejt.mp3', 'Fli shpejt — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Gjumi i thellë', 'Gjumi', 'meditime-per-trupin', 'gjumi', 600, 'meditime/meditime-per-trupin/gjumi-i-thelle.mp3', 'Gjumi i thellë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Pas pagjumësisë', 'Gjumi', 'meditime-per-trupin', 'gjumi', 600, 'meditime/meditime-per-trupin/pas-pagjumesise.mp3', 'Pas pagjumësisë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Pas zgjimit natën', 'Gjumi', 'meditime-per-trupin', 'gjumi', 600, 'meditime/meditime-per-trupin/pas-zgjimit-naten.mp3', 'Pas zgjimit natën — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Rikthe ritmin cirkadian', 'Gjumi', 'meditime-per-trupin', 'gjumi', 600, 'meditime/meditime-per-trupin/rikthe-ritmin-cirkadian.mp3', 'Rikthe ritmin cirkadian — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Zgjohu me energji', 'Gjumi', 'meditime-per-trupin', 'gjumi', 600, 'meditime/meditime-per-trupin/zgjohu-me-energji.mp3', 'Zgjohu me energji — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Energjia e mëngjesit', 'Energjia', 'meditime-per-trupin', 'energji-e-larte', 600, 'meditime/meditime-per-trupin/energjia-e-mengjesit.mp3', 'Energjia e mëngjesit — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Pasdite pa lodhje', 'Energjia', 'meditime-per-trupin', 'energji-e-larte', 600, 'meditime/meditime-per-trupin/pasdite-pa-lodhje.mp3', 'Pasdite pa lodhje — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Pas punës', 'Energjia', 'meditime-per-trupin', 'energji-e-larte', 600, 'meditime/meditime-per-trupin/pas-punes.mp3', 'Pas punës — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Pas udhëtimit', 'Energjia', 'meditime-per-trupin', 'energji-e-larte', 600, 'meditime/meditime-per-trupin/pas-udhetimit.mp3', 'Pas udhëtimit — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Pas stresit', 'Energjia', 'meditime-per-trupin', 'energji-e-larte', 600, 'meditime/meditime-per-trupin/pas-stresit.mp3', 'Pas stresit — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Rimbush energjinë', 'Energjia', 'meditime-per-trupin', 'energji-e-larte', 600, 'meditime/meditime-per-trupin/rimbush-energjine.mp3', 'Rimbush energjinë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Ndjehu i lehtë', 'Energjia', 'meditime-per-trupin', 'energji-e-larte', 600, 'meditime/meditime-per-trupin/ndjehu-i-lehte.mp3', 'Ndjehu i lehtë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Manifesto bollëk', 'Manifestimi', 'meditime-manifestimi', 'manifestim', 600, 'meditime/meditime-manifestimi/manifesto-bollek.mp3', 'Manifesto bollëk — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Manifesto partner', 'Manifestimi', 'meditime-manifestimi', 'manifestim', 600, 'meditime/meditime-manifestimi/manifesto-partner.mp3', 'Manifesto partner — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Manifesto shtëpi', 'Manifestimi', 'meditime-manifestimi', 'manifestim', 600, 'meditime/meditime-manifestimi/manifesto-shtepi.mp3', 'Manifesto shtëpi — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Manifesto punë', 'Manifestimi', 'meditime-manifestimi', 'manifestim', 600, 'meditime/meditime-manifestimi/manifesto-pune.mp3', 'Manifesto punë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Manifesto klientë', 'Manifestimi', 'meditime-manifestimi', 'manifestim', 600, 'meditime/meditime-manifestimi/manifesto-kliente.mp3', 'Manifesto klientë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Manifesto shëndet', 'Manifestimi', 'meditime-manifestimi', 'manifestim', 600, 'meditime/meditime-manifestimi/manifesto-shendet.mp3', 'Manifesto shëndet — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Manifesto sukses', 'Manifestimi', 'meditime-manifestimi', 'manifestim', 600, 'meditime/meditime-manifestimi/manifesto-sukses.mp3', 'Manifesto sukses — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Ankth i përgjithshëm', 'Ankthi', 'eft-tapping', 'ankth-panik', 600, 'meditime/eft-tapping/ankth-i-pergjithshem.mp3', 'Ankth i përgjithshëm — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Ankth para fluturimit', 'Ankthi', 'eft-tapping', 'ankth-panik', 600, 'meditime/eft-tapping/ankth-para-fluturimit.mp3', 'Ankth para fluturimit — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Ankth para provimit', 'Ankthi', 'eft-tapping', 'ankth-panik', 600, 'meditime/eft-tapping/ankth-para-provimit.mp3', 'Ankth para provimit — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Ankth para prezantimit', 'Ankthi', 'eft-tapping', 'ankth-panik', 600, 'meditime/eft-tapping/ankth-para-prezantimit.mp3', 'Ankth para prezantimit — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Ankth social', 'Ankthi', 'eft-tapping', 'ankth-panik', 600, 'meditime/eft-tapping/ankth-social.mp3', 'Ankth social — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Ankth në trafik', 'Ankthi', 'eft-tapping', 'ankth-panik', 600, 'meditime/eft-tapping/ankth-ne-trafik.mp3', 'Ankth në trafik — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Ankth para gjumit', 'Ankthi', 'eft-tapping', 'ankth-panik', 600, 'meditime/eft-tapping/ankth-para-gjumit.mp3', 'Ankth para gjumit — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Pas debatit', 'Marrëdhënie', 'eft-tapping', 'marredheniet', 600, 'meditime/eft-tapping/pas-debatit.mp3', 'Pas debatit — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Para një bisede të vështirë', 'Marrëdhënie', 'eft-tapping', 'marredheniet', 600, 'meditime/eft-tapping/para-nje-bisede-te-veshtire.mp3', 'Para një bisede të vështirë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Pas tradhtisë', 'Marrëdhënie', 'eft-tapping', 'marredheniet', 600, 'meditime/eft-tapping/pas-tradhtise.mp3', 'Pas tradhtisë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Xhelozia', 'Marrëdhënie', 'eft-tapping', 'marredheniet', 600, 'meditime/eft-tapping/xhelozia.mp3', 'Xhelozia — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Frika nga refuzimi', 'Marrëdhënie', 'eft-tapping', 'marredheniet', 600, 'meditime/eft-tapping/frika-nga-refuzimi.mp3', 'Frika nga refuzimi — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Frika nga braktisja', 'Marrëdhënie', 'eft-tapping', 'marredheniet', 600, 'meditime/eft-tapping/frika-nga-braktisja.mp3', 'Frika nga braktisja — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Frika nga shitja', 'Biznes', 'eft-tapping', 'fokus', 600, 'meditime/eft-tapping/frika-nga-shitja.mp3', 'Frika nga shitja — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Frika nga refuzimi', 'Biznes', 'eft-tapping', 'fokus', 600, 'meditime/eft-tapping/frika-nga-refuzimi-2.mp3', 'Frika nga refuzimi — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Frika nga çmimet e larta', 'Biznes', 'eft-tapping', 'fokus', 600, 'meditime/eft-tapping/frika-nga-cmimet-e-larta.mp3', 'Frika nga çmimet e larta — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Frika nga suksesi', 'Biznes', 'eft-tapping', 'fokus', 600, 'meditime/eft-tapping/frika-nga-suksesi.mp3', 'Frika nga suksesi — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Frika nga dështimi', 'Biznes', 'eft-tapping', 'fokus', 600, 'meditime/eft-tapping/frika-nga-deshtimi.mp3', 'Frika nga dështimi — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Sindroma e mashtruesit', 'Biznes', 'eft-tapping', 'fokus', 600, 'meditime/eft-tapping/sindroma-e-mashtruesit.mp3', 'Sindroma e mashtruesit — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Dhimbje koke', 'Trupi', 'eft-tapping', 'shendeti', 600, 'meditime/eft-tapping/dhimbje-koke.mp3', 'Dhimbje koke — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Dhimbje qafe', 'Trupi', 'eft-tapping', 'shendeti', 600, 'meditime/eft-tapping/dhimbje-qafe.mp3', 'Dhimbje qafe — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Dhimbje shpine', 'Trupi', 'eft-tapping', 'shendeti', 600, 'meditime/eft-tapping/dhimbje-shpine.mp3', 'Dhimbje shpine — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Migrenë', 'Trupi', 'eft-tapping', 'shendeti', 600, 'meditime/eft-tapping/migrene.mp3', 'Migrenë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Tension muskulor', 'Trupi', 'eft-tapping', 'shendeti', 600, 'meditime/eft-tapping/tension-muskulor.mp3', 'Tension muskulor — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Dëshira për sheqer', 'Varësi', 'eft-tapping', 'varesite', 600, 'meditime/eft-tapping/deshira-per-sheqer.mp3', 'Dëshira për sheqer — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Dëshira për cigare', 'Varësi', 'eft-tapping', 'varesite', 600, 'meditime/eft-tapping/deshira-per-cigare.mp3', 'Dëshira për cigare — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Overeating', 'Varësi', 'eft-tapping', 'varesite', 600, 'meditime/eft-tapping/overeating.mp3', 'Overeating — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Telefoni', 'Varësi', 'eft-tapping', 'varesite', 600, 'meditime/eft-tapping/telefoni.mp3', 'Telefoni — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Rrjetet sociale', 'Varësi', 'eft-tapping', 'varesite', 600, 'meditime/eft-tapping/rrjetet-sociale.mp3', 'Rrjetet sociale — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Energji në mëngjes', 'Aktivizim', 'frymemarrje', 'energji-e-larte', 600, 'meditime/frymemarrje/energji-ne-mengjes.mp3', 'Energji në mëngjes — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Aktivizo motivimin', 'Aktivizim', 'frymemarrje', 'energji-e-larte', 600, 'meditime/frymemarrje/aktivizo-motivimin.mp3', 'Aktivizo motivimin — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Para palestrës', 'Aktivizim', 'frymemarrje', 'energji-e-larte', 600, 'meditime/frymemarrje/para-palestres.mp3', 'Para palestrës — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Para punës', 'Aktivizim', 'frymemarrje', 'energji-e-larte', 600, 'meditime/frymemarrje/para-punes.mp3', 'Para punës — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Për panik', 'Qetësim', 'frymemarrje', 'stres', 600, 'meditime/frymemarrje/per-panik.mp3', 'Për panik — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Për ankth', 'Qetësim', 'frymemarrje', 'stres', 600, 'meditime/frymemarrje/per-ankth.mp3', 'Për ankth — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Për stres', 'Qetësim', 'frymemarrje', 'stres', 600, 'meditime/frymemarrje/per-stres.mp3', 'Për stres — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Pas debatit', 'Qetësim', 'frymemarrje', 'stres', 600, 'meditime/frymemarrje/pas-debatit.mp3', 'Pas debatit — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Në trafik', 'Qetësim', 'frymemarrje', 'stres', 600, 'meditime/frymemarrje/ne-trafik.mp3', 'Në trafik — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Fokus', 'Performancë', 'frymemarrje', 'fokus', 600, 'meditime/frymemarrje/fokus.mp3', 'Fokus — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Kreativitet', 'Performancë', 'frymemarrje', 'fokus', 600, 'meditime/frymemarrje/kreativitet.mp3', 'Kreativitet — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Para provimit', 'Performancë', 'frymemarrje', 'fokus', 600, 'meditime/frymemarrje/para-provimit.mp3', 'Para provimit — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Para negociatës', 'Performancë', 'frymemarrje', 'fokus', 600, 'meditime/frymemarrje/para-negociates.mp3', 'Para negociatës — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Para sportit', 'Performancë', 'frymemarrje', 'fokus', 600, 'meditime/frymemarrje/para-sportit.mp3', 'Para sportit — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Manifesto bollëk', 'Manifestim', 'frymemarrje', 'manifestim', 600, 'meditime/frymemarrje/manifesto-bollek.mp3', 'Manifesto bollëk — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Manifesto shtëpi', 'Manifestim', 'frymemarrje', 'manifestim', 600, 'meditime/frymemarrje/manifesto-shtepi.mp3', 'Manifesto shtëpi — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Manifesto klientë', 'Manifestim', 'frymemarrje', 'manifestim', 600, 'meditime/frymemarrje/manifesto-kliente.mp3', 'Manifesto klientë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Manifesto partner', 'Manifestim', 'frymemarrje', 'manifestim', 600, 'meditime/frymemarrje/manifesto-partner.mp3', 'Manifesto partner — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Manifesto shëndet', 'Manifestim', 'frymemarrje', 'manifestim', 600, 'meditime/frymemarrje/manifesto-shendet.mp3', 'Manifesto shëndet — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Frymëmarrje vagale', 'Shërim', 'frymemarrje', 'shendeti', 600, 'meditime/frymemarrje/frymemarrje-vagale.mp3', 'Frymëmarrje vagale — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Frymëmarrje diafragmatike', 'Shërim', 'frymemarrje', 'shendeti', 600, 'meditime/frymemarrje/frymemarrje-diafragmatike.mp3', 'Frymëmarrje diafragmatike — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Coherence breathing', 'Shërim', 'frymemarrje', 'shendeti', 600, 'meditime/frymemarrje/coherence-breathing.mp3', 'Coherence breathing — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Box breathing', 'Shërim', 'frymemarrje', 'shendeti', 600, 'meditime/frymemarrje/box-breathing.mp3', 'Box breathing — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Resonant breathing', 'Shërim', 'frymemarrje', 'shendeti', 600, 'meditime/frymemarrje/resonant-breathing.mp3', 'Resonant breathing — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Shkundja neurogjene', 'Lirim & Çlirim', 'teknika-somatike', 'shendeti', 600, 'meditime/teknika-somatike/shkundja-neurogjene.mp3', 'Shkundja neurogjene — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Trauma release', 'Lirim & Çlirim', 'teknika-somatike', 'shendeti', 600, 'meditime/teknika-somatike/trauma-release.mp3', 'Trauma release — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Somatic shaking', 'Lirim & Çlirim', 'teknika-somatike', 'shendeti', 600, 'meditime/teknika-somatike/somatic-shaking.mp3', 'Somatic shaking — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Somatic orienting', 'Lirim & Çlirim', 'teknika-somatike', 'shendeti', 600, 'meditime/teknika-somatike/somatic-orienting.mp3', 'Somatic orienting — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Pendulation', 'Lirim & Çlirim', 'teknika-somatike', 'shendeti', 600, 'meditime/teknika-somatike/pendulation.mp3', 'Pendulation — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Titration', 'Lirim & Çlirim', 'teknika-somatike', 'shendeti', 600, 'meditime/teknika-somatike/titration.mp3', 'Titration — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Grounding', 'Tokëzim & Lëvizje', 'meditim-ne-ecje', 'qetesim', 600, 'meditime/meditim-ne-ecje/grounding.mp3', 'Grounding — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Body scan', 'Tokëzim & Lëvizje', 'meditim-ne-ecje', 'qetesim', 600, 'meditime/meditim-ne-ecje/body-scan.mp3', 'Body scan — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Somatic walking', 'Tokëzim & Lëvizje', 'meditim-ne-ecje', 'qetesim', 600, 'meditime/meditim-ne-ecje/somatic-walking.mp3', 'Somatic walking — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Somatic dancing', 'Tokëzim & Lëvizje', 'meditim-ne-ecje', 'qetesim', 600, 'meditime/meditim-ne-ecje/somatic-dancing.mp3', 'Somatic dancing — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Lirim i nofullës', 'Lirim i zonave', 'teknika-somatike', 'shendeti', 600, 'meditime/teknika-somatike/lirim-i-nofulles.mp3', 'Lirim i nofullës — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Lirim i legenit', 'Lirim i zonave', 'teknika-somatike', 'shendeti', 600, 'meditime/teknika-somatike/lirim-i-legenit.mp3', 'Lirim i legenit — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Lirim i diafragmës', 'Lirim i zonave', 'teknika-somatike', 'shendeti', 600, 'meditime/teknika-somatike/lirim-i-diafragmes.mp3', 'Lirim i diafragmës — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Lirim i kraharorit', 'Lirim i zonave', 'teknika-somatike', 'shendeti', 600, 'meditime/teknika-somatike/lirim-i-kraharorit.mp3', 'Lirim i kraharorit — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Hapja e qafës', 'Lirim i zonave', 'teknika-somatike', 'shendeti', 600, 'meditime/teknika-somatike/hapja-e-qafes.mp3', 'Hapja e qafës — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Mbush aurën', 'Aura & Mbrojtje', 'teknika-energjetike', 'qetesim', 600, 'meditime/teknika-energjetike/mbush-auren.mp3', 'Mbush aurën — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Pastro aurën', 'Aura & Mbrojtje', 'teknika-energjetike', 'qetesim', 600, 'meditime/teknika-energjetike/pastro-auren.mp3', 'Pastro aurën — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Mbrojtje energjitike', 'Aura & Mbrojtje', 'teknika-energjetike', 'qetesim', 600, 'meditime/teknika-energjetike/mbrojtje-energjitike.mp3', 'Mbrojtje energjitike — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Kthe energjinë tek vetja', 'Aura & Mbrojtje', 'teknika-energjetike', 'qetesim', 600, 'meditime/teknika-energjetike/kthe-energjine-tek-vetja.mp3', 'Kthe energjinë tek vetja — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Liro lidhjet toksike', 'Aura & Mbrojtje', 'teknika-energjetike', 'qetesim', 600, 'meditime/teknika-energjetike/liro-lidhjet-toksike.mp3', 'Liro lidhjet toksike — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Hap zemrën', 'Aktivizim', 'teknika-energjetike', 'zemra-plot', 600, 'meditime/teknika-energjetike/hap-zemren.mp3', 'Hap zemrën — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Aktivizo intuitën', 'Aktivizim', 'teknika-energjetike', 'intuita', 600, 'meditime/teknika-energjetike/aktivizo-intuiten.mp3', 'Aktivizo intuitën — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Aktivizo bollëkun', 'Aktivizim', 'teknika-energjetike', 'zemra-plot', 600, 'meditime/teknika-energjetike/aktivizo-bollekun.mp3', 'Aktivizo bollëkun — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Balanco chakrat', 'Aktivizim', 'teknika-energjetike', 'zemra-plot', 600, 'meditime/teknika-energjetike/balanco-chakrat.mp3', 'Balanco chakrat — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Tokëzim', 'Vibracioni', 'teknika-energjetike', 'bolleku', 600, 'meditime/teknika-energjetike/tokezim.mp3', 'Tokëzim — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Qendra e trupit', 'Vibracioni', 'teknika-energjetike', 'bolleku', 600, 'meditime/teknika-energjetike/qendra-e-trupit.mp3', 'Qendra e trupit — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Rrit vibracionin', 'Vibracioni', 'teknika-energjetike', 'bolleku', 600, 'meditime/teknika-energjetike/rrit-vibracionin.mp3', 'Rrit vibracionin — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Praktika me duar', 'Vibracioni', 'teknika-energjetike', 'bolleku', 600, 'meditime/teknika-energjetike/praktika-me-duar.mp3', 'Praktika me duar — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Vetë-shërim energjetik', 'Vibracioni', 'teknika-energjetike', 'bolleku', 600, 'meditime/teknika-energjetike/vete-sherim-energjetik.mp3', 'Vetë-shërim energjetik — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Takimi me veten e ardhshme', 'Vetja', 'vizualizim', 'vetja-e-ardhme', 600, 'meditime/vizualizim/takimi-me-veten-e-ardhshme.mp3', 'Takimi me veten e ardhshme — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Versioni më i mirë i vetes', 'Vetja', 'vizualizim', 'vetja-e-ardhme', 600, 'meditime/vizualizim/versioni-me-i-mire-i-vetes.mp3', 'Versioni më i mirë i vetes — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Fëmija i brendshëm', 'Vetja', 'vizualizim', 'vetja-e-ardhme', 600, 'meditime/vizualizim/femija-i-brendshem.mp3', 'Fëmija i brendshëm — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Takimi me mentorin', 'Vetja', 'vizualizim', 'vetja-e-ardhme', 600, 'meditime/vizualizim/takimi-me-mentorin.mp3', 'Takimi me mentorin — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Dita perfekte', 'Jeta ideale', 'vizualizim', 'jeta-ideale', 600, 'meditime/vizualizim/dita-perfekte.mp3', 'Dita perfekte — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Shtëpia ideale', 'Jeta ideale', 'vizualizim', 'jeta-ideale', 600, 'meditime/vizualizim/shtepia-ideale.mp3', 'Shtëpia ideale — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Biznesi ideal', 'Jeta ideale', 'vizualizim', 'jeta-ideale', 600, 'meditime/vizualizim/biznesi-ideal.mp3', 'Biznesi ideal — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Partneri ideal', 'Jeta ideale', 'vizualizim', 'jeta-ideale', 600, 'meditime/vizualizim/partneri-ideal.mp3', 'Partneri ideal — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Trupi ideal', 'Jeta ideale', 'vizualizim', 'jeta-ideale', 600, 'meditime/vizualizim/trupi-ideal.mp3', 'Trupi ideal — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Skenari i suksesit', 'Jeta ideale', 'vizualizim', 'jeta-ideale', 600, 'meditime/vizualizim/skenari-i-suksesit.mp3', 'Skenari i suksesit — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Bollëk', 'Zhvillim personal', 'afirmime', 'dashuria-vetes', 600, 'meditime/afirmime/bollek.mp3', 'Bollëk — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Vetëvlerësim', 'Zhvillim personal', 'afirmime', 'dashuria-vetes', 600, 'meditime/afirmime/vetevleresim.mp3', 'Vetëvlerësim — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Dashuri', 'Zhvillim personal', 'afirmime', 'dashuria-vetes', 600, 'meditime/afirmime/dashuri.mp3', 'Dashuri — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Shëndet', 'Zhvillim personal', 'afirmime', 'dashuria-vetes', 600, 'meditime/afirmime/shendet.mp3', 'Shëndet — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Manifestim', 'Zhvillim personal', 'afirmime', 'dashuria-vetes', 600, 'meditime/afirmime/manifestim.mp3', 'Manifestim — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Falje', 'Zhvillim personal', 'afirmime', 'falja', 600, 'meditime/afirmime/falje.mp3', 'Falje — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Besim', 'Zhvillim personal', 'afirmime', 'dashuria-vetes', 600, 'meditime/afirmime/besim.mp3', 'Besim — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Prindërim', 'Role', 'afirmime', 'energji-e-larte', 600, 'meditime/afirmime/prinderim.mp3', 'Prindërim — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Biznes', 'Role', 'afirmime', 'energji-e-larte', 600, 'meditime/afirmime/biznes.mp3', 'Biznes — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Karrierë', 'Role', 'afirmime', 'energji-e-larte', 600, 'meditime/afirmime/karriere.mp3', 'Karrierë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Gratë', 'Role', 'afirmime', 'energji-e-larte', 600, 'meditime/afirmime/grate.mp3', 'Gratë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Burrat', 'Role', 'afirmime', 'energji-e-larte', 600, 'meditime/afirmime/burrat.mp3', 'Burrat — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Fëmijët', 'Role', 'afirmime', 'energji-e-larte', 600, 'meditime/afirmime/femijet.mp3', 'Fëmijët — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Studentët', 'Role', 'afirmime', 'energji-e-larte', 600, 'meditime/afirmime/studentet.mp3', 'Studentët — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Gjumi', 'Transformim', 'hipnoterapi', 'shero-te-kaluaren', 600, 'meditime/hipnoterapi/gjumi.mp3', 'Gjumi — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Humbje peshe', 'Transformim', 'hipnoterapi', 'shero-te-kaluaren', 600, 'meditime/hipnoterapi/humbje-peshe.mp3', 'Humbje peshe — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Vetëbesim', 'Transformim', 'hipnoterapi', 'shero-te-kaluaren', 600, 'meditime/hipnoterapi/vetebesim.mp3', 'Vetëbesim — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Ndal duhanin', 'Transformim', 'hipnoterapi', 'shero-te-kaluaren', 600, 'meditime/hipnoterapi/ndal-duhanin.mp3', 'Ndal duhanin — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Manifestim', 'Transformim', 'hipnoterapi', 'shero-te-kaluaren', 600, 'meditime/hipnoterapi/manifestim.mp3', 'Manifestim — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Kujtesë', 'Transformim', 'hipnoterapi', 'shero-te-kaluaren', 600, 'meditime/hipnoterapi/kujtese.mp3', 'Kujtesë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Kreativitet', 'Transformim', 'hipnoterapi', 'shero-te-kaluaren', 600, 'meditime/hipnoterapi/kreativitet.mp3', 'Kreativitet — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Shërim emocional', 'Transformim', 'hipnoterapi', 'shero-te-kaluaren', 600, 'meditime/hipnoterapi/sherim-emocional.mp3', 'Shërim emocional — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('3 minuta energji', 'Mëngjes', 'meditime-per-trupin', 'mengjes', 180, 'meditime/meditime-per-trupin/3-minuta-energji.mp3', '3 minuta energji — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Vendos qëllimin', 'Mëngjes', 'meditime-per-trupin', 'mengjes', 180, 'meditime/meditime-per-trupin/vendos-qellimin.mp3', 'Vendos qëllimin — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Aktivizo zemrën', 'Mëngjes', 'meditime-per-trupin', 'mengjes', 180, 'meditime/meditime-per-trupin/aktivizo-zemren.mp3', 'Aktivizo zemrën — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Në trafik', 'Në makinë', 'meditime-per-trupin', 'situata', 300, 'meditime/meditime-per-trupin/ne-trafik.mp3', 'Në trafik — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Para punës', 'Në makinë', 'meditime-per-trupin', 'situata', 300, 'meditime/meditime-per-trupin/para-punes.mp3', 'Para punës — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Pas punës', 'Në makinë', 'meditime-per-trupin', 'situata', 300, 'meditime/meditime-per-trupin/pas-punes-2.mp3', 'Pas punës — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Para mbledhjes', 'Në punë', 'meditime-per-trupin', 'situata', 300, 'meditime/meditime-per-trupin/para-mbledhjes.mp3', 'Para mbledhjes — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Pas mbledhjes', 'Në punë', 'meditime-per-trupin', 'situata', 300, 'meditime/meditime-per-trupin/pas-mbledhjes.mp3', 'Pas mbledhjes — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Kur je i stresuar', 'Në punë', 'meditime-per-trupin', 'situata', 300, 'meditime/meditime-per-trupin/kur-je-i-stresuar.mp3', 'Kur je i stresuar — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Kur nuk ke fokus', 'Në punë', 'meditime-per-trupin', 'situata', 300, 'meditime/meditime-per-trupin/kur-nuk-ke-fokus.mp3', 'Kur nuk ke fokus — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Pas debatit', 'Në shtëpi', 'meditime-per-trupin', 'mbremje', 300, 'meditime/meditime-per-trupin/pas-debatit.mp3', 'Pas debatit — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Para gjumit', 'Në shtëpi', 'meditime-per-trupin', 'mbremje', 300, 'meditime/meditime-per-trupin/para-gjumit.mp3', 'Para gjumit — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Para darkës', 'Në shtëpi', 'meditime-per-trupin', 'mbremje', 300, 'meditime/meditime-per-trupin/para-darkes.mp3', 'Para darkës — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Pas lajmit të keq', 'Në shtëpi', 'meditime-per-trupin', 'mbremje', 300, 'meditime/meditime-per-trupin/pas-lajmit-te-keq.mp3', 'Pas lajmit të keq — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Sulm paniku', 'Krizë akute', 'frymemarrje', 'emergjence', 480, 'meditime/frymemarrje/sulm-paniku.mp3', 'Sulm paniku — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Zemërim ekstrem', 'Krizë akute', 'frymemarrje', 'emergjence', 480, 'meditime/frymemarrje/zemerim-ekstrem.mp3', 'Zemërim ekstrem — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Ankth akut', 'Krizë akute', 'frymemarrje', 'emergjence', 480, 'meditime/frymemarrje/ankth-akut.mp3', 'Ankth akut — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Lajm i keq', 'Krizë akute', 'frymemarrje', 'emergjence', 480, 'meditime/frymemarrje/lajm-i-keq.mp3', 'Lajm i keq — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Humbje', 'Krizë akute', 'frymemarrje', 'emergjence', 480, 'meditime/frymemarrje/humbje.mp3', 'Humbje — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Frikë', 'Krizë akute', 'frymemarrje', 'emergjence', 480, 'meditime/frymemarrje/frike.mp3', 'Frikë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Krizë emocionale', 'Krizë akute', 'frymemarrje', 'emergjence', 480, 'meditime/frymemarrje/krize-emocionale.mp3', 'Krizë emocionale — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Të qara', 'Krizë akute', 'frymemarrje', 'emergjence', 480, 'meditime/frymemarrje/te-qara.mp3', 'Të qara — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Overthinking', 'Krizë akute', 'frymemarrje', 'emergjence', 480, 'meditime/frymemarrje/overthinking.mp3', 'Overthinking — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Dhimbje koke', 'Dhimbje & Tension', 'rigjenerim-dhe-sherim', 'shendeti', 600, 'meditime/rigjenerim-dhe-sherim/dhimbje-koke.mp3', 'Dhimbje koke — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Migrenë', 'Dhimbje & Tension', 'rigjenerim-dhe-sherim', 'shendeti', 600, 'meditime/rigjenerim-dhe-sherim/migrene.mp3', 'Migrenë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Tension', 'Dhimbje & Tension', 'rigjenerim-dhe-sherim', 'shendeti', 600, 'meditime/rigjenerim-dhe-sherim/tension.mp3', 'Tension — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Tinnitus', 'Dhimbje & Tension', 'rigjenerim-dhe-sherim', 'shendeti', 600, 'meditime/rigjenerim-dhe-sherim/tinnitus.mp3', 'Tinnitus — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('IBS', 'Gjendje kronike', 'rigjenerim-dhe-sherim', 'shendeti', 600, 'meditime/rigjenerim-dhe-sherim/ibs.mp3', 'IBS — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Hashimoto', 'Gjendje kronike', 'rigjenerim-dhe-sherim', 'shendeti', 600, 'meditime/rigjenerim-dhe-sherim/hashimoto.mp3', 'Hashimoto — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Inflamacion', 'Gjendje kronike', 'rigjenerim-dhe-sherim', 'shendeti', 600, 'meditime/rigjenerim-dhe-sherim/inflamacion.mp3', 'Inflamacion — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Lodhje', 'Gjendje kronike', 'rigjenerim-dhe-sherim', 'shendeti', 600, 'meditime/rigjenerim-dhe-sherim/lodhje.mp3', 'Lodhje — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Mbështetje gjatë rikuperimit', 'Gjendje kronike', 'rigjenerim-dhe-sherim', 'shendeti', 600, 'meditime/rigjenerim-dhe-sherim/mbeshtetje-gjate-rikuperimit.mp3', 'Mbështetje gjatë rikuperimit — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Menopauzë', 'Cikli & Hormonet', 'rigjenerim-dhe-sherim', 'dashuria-vetes', 600, 'meditime/rigjenerim-dhe-sherim/menopauze.mp3', 'Menopauzë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('PMS', 'Cikli & Hormonet', 'rigjenerim-dhe-sherim', 'dashuria-vetes', 600, 'meditime/rigjenerim-dhe-sherim/pms.mp3', 'PMS — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Çifti', 'Lidhjet', 'meditime-per-zemren', 'marredheniet', 600, 'meditime/meditime-per-zemren/cifti.mp3', 'Çifti — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Prindërimi', 'Lidhjet', 'meditime-per-zemren', 'marredheniet', 600, 'meditime/meditime-per-zemren/prinderimi.mp3', 'Prindërimi — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Adoleshentët', 'Lidhjet', 'meditime-per-zemren', 'adoleshentet', 600, 'meditime/meditime-per-zemren/adoleshentet.mp3', 'Adoleshentët — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Intimiteti', 'Lidhjet', 'meditime-per-zemren', 'marredheniet', 600, 'meditime/meditime-per-zemren/intimiteti.mp3', 'Intimiteti — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Miqësia', 'Lidhjet', 'meditime-per-zemren', 'marredheniet', 600, 'meditime/meditime-per-zemren/miqesia.mp3', 'Miqësia — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Kufijtë', 'Brenda vetes', 'meditime-per-zemren', 'dashuria-vetes', 600, 'meditime/meditime-per-zemren/kufijte.mp3', 'Kufijtë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Komunikimi', 'Brenda vetes', 'meditime-per-zemren', 'dashuria-vetes', 600, 'meditime/meditime-per-zemren/komunikimi.mp3', 'Komunikimi — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Falja', 'Brenda vetes', 'meditime-per-zemren', 'falja', 600, 'meditime/meditime-per-zemren/falja.mp3', 'Falja — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Vetmia', 'Brenda vetes', 'meditime-per-zemren', 'dashuria-vetes', 600, 'meditime/meditime-per-zemren/vetmia.mp3', 'Vetmia — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('CEO Mindset', 'Mendësia', 'meditime-per-trurin', 'fokus', 600, 'meditime/meditime-per-trurin/ceo-mindset.mp3', 'CEO Mindset — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Sipërmarrësi', 'Mendësia', 'meditime-per-trurin', 'fokus', 600, 'meditime/meditime-per-trurin/sipermarresi.mp3', 'Sipërmarrësi — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Lideri', 'Mendësia', 'meditime-per-trurin', 'fokus', 600, 'meditime/meditime-per-trurin/lideri.mp3', 'Lideri — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Vendimmarrja', 'Mendësia', 'meditime-per-trurin', 'fokus', 600, 'meditime/meditime-per-trurin/vendimmarrja.mp3', 'Vendimmarrja — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Shitjet', 'Aftësi', 'meditime-per-trurin', 'fokus', 600, 'meditime/meditime-per-trurin/shitjet.mp3', 'Shitjet — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Marketingu', 'Aftësi', 'meditime-per-trurin', 'fokus', 600, 'meditime/meditime-per-trurin/marketingu.mp3', 'Marketingu — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Kreativiteti', 'Aftësi', 'meditime-per-trurin', 'fokus', 600, 'meditime/meditime-per-trurin/kreativiteti.mp3', 'Kreativiteti — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Delegimi', 'Aftësi', 'meditime-per-trurin', 'fokus', 600, 'meditime/meditime-per-trurin/delegimi.mp3', 'Delegimi — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Produktiviteti', 'Aftësi', 'meditime-per-trurin', 'fokus', 600, 'meditime/meditime-per-trurin/produktiviteti.mp3', 'Produktiviteti — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Burnout', 'Aftësi', 'meditime-per-trurin', 'fokus', 600, 'meditime/meditime-per-trurin/burnout.mp3', 'Burnout — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Para gjumit', 'Për fëmijë', 'meditime-per-trupin', 'femijet-8-12', 360, 'meditime/meditime-per-trupin/para-gjumit-2.mp3', 'Para gjumit — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Ankthi', 'Për fëmijë', 'meditime-per-trupin', 'femijet-8-12', 360, 'meditime/meditime-per-trupin/ankthi.mp3', 'Ankthi — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Vetëbesimi', 'Për fëmijë', 'meditime-per-trupin', 'femijet-8-12', 360, 'meditime/meditime-per-trupin/vetebesimi.mp3', 'Vetëbesimi — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Përqendrimi', 'Për fëmijë', 'meditime-per-trupin', 'femijet-8-12', 360, 'meditime/meditime-per-trupin/perqendrimi.mp3', 'Përqendrimi — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Mirënjohja', 'Për fëmijë', 'meditime-per-trupin', 'femijet-8-12', 360, 'meditime/meditime-per-trupin/mirenjohja.mp3', 'Mirënjohja — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Menaxhimi i emocioneve', 'Për fëmijë', 'meditime-per-trupin', 'femijet-8-12', 360, 'meditime/meditime-per-trupin/menaxhimi-i-emocioneve.mp3', 'Menaxhimi i emocioneve — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('Meditime familjare', 'Familje', 'meditime-per-trupin', 'marredheniet', 480, 'meditime/meditime-per-trupin/meditime-familjare.mp3', 'Meditime familjare — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('7 ditë kundër ankthit', 'Sfidat', 'meditime-riprogramimi', 'varesite', 600, 'meditime/meditime-riprogramimi/7-dite-kunder-ankthit.mp3', '7 ditë kundër ankthit — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('21 ditë vetëdashurie', 'Sfidat', 'meditime-riprogramimi', 'varesite', 600, 'meditime/meditime-riprogramimi/21-dite-vetedashurie.mp3', '21 ditë vetëdashurie — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('30 ditë bollëku', 'Sfidat', 'meditime-riprogramimi', 'varesite', 600, 'meditime/meditime-riprogramimi/30-dite-bolleku.mp3', '30 ditë bollëku — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('30 ditë disipline', 'Sfidat', 'meditime-riprogramimi', 'varesite', 600, 'meditime/meditime-riprogramimi/30-dite-disipline.mp3', '30 ditë disipline — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('7 ditë gjumë', 'Sfidat', 'meditime-riprogramimi', 'varesite', 600, 'meditime/meditime-riprogramimi/7-dite-gjume.mp3', '7 ditë gjumë — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('14 ditë zemra', 'Sfidat', 'meditime-riprogramimi', 'varesite', 600, 'meditime/meditime-riprogramimi/14-dite-zemra.mp3', '14 ditë zemra — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('21 ditë meditimi', 'Sfidat', 'meditime-riprogramimi', 'varesite', 600, 'meditime/meditime-riprogramimi/21-dite-meditimi.mp3', '21 ditë meditimi — praktikë e udhëhequr nga Arte Gogo.', 1),
  ('40 ditë transformimi', 'Sfidat', 'meditime-riprogramimi', 'varesite', 600, 'meditime/meditime-riprogramimi/40-dite-transformimi.mp3', '40 ditë transformimi — praktikë e udhëhequr nga Arte Gogo.', 1);

INSERT INTO meditations
  (title, subgroup, technique_id, category_id, duration_sec,
   audio_url, description, is_premium, narrator, published_at)
SELECT t.title, t.subgroup, tec.id, cat.id, t.duration_sec,
       t.audio_url, t.description, t.is_premium, 'Arte Gogo', NOW()
  FROM tmp_meditations t
  JOIN techniques tec ON tec.slug = t.technique_slug
  JOIN categories cat ON cat.slug = t.category_slug;

DROP TEMPORARY TABLE IF EXISTS tmp_meditations;

-- Kontroll: duhet të kthejë 244 dhe 0.
SELECT COUNT(*) AS meditime, SUM(is_premium = 0) AS falas FROM meditations;
